apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: sample
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    securityContext:
      privileged: true
  restartPolicy: Always