// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkloadIdentity.Data;

#nullable disable

namespace WorkloadIdentity.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20230124131107_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkloadIdentity.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = "991e0c2f-a768-40b9-9eaa-b7c31eb3fcc4",
                            Company = "Microsoft",
                            Created = new DateTime(2023, 1, 21, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5520),
                            Level = "100",
                            SourceId = 1001,
                            Updated = new DateTime(2023, 1, 24, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5556)
                        },
                        new
                        {
                            Id = "b84178a0-b0ff-4721-96cc-5d271d93f6b9",
                            Company = "Google",
                            Created = new DateTime(2023, 1, 19, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5558),
                            Level = "100",
                            SourceId = 1002,
                            Updated = new DateTime(2023, 1, 24, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5559)
                        },
                        new
                        {
                            Id = "fbf6dc01-93f9-4772-891f-46e5a79d6e2a",
                            Company = "Apple",
                            Created = new DateTime(2023, 1, 17, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5561),
                            Level = "100",
                            SourceId = 1003,
                            Updated = new DateTime(2023, 1, 24, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5562)
                        },
                        new
                        {
                            Id = "5c3ac12f-ec83-449e-a37e-de7442cde7da",
                            Company = "Amazon",
                            Created = new DateTime(2023, 1, 15, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5564),
                            Level = "100",
                            SourceId = 1004,
                            Updated = new DateTime(2023, 1, 24, 14, 11, 6, 986, DateTimeKind.Local).AddTicks(5566)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
